server:
    port: 8888
spring:
    application: 
        name: config-servervice
    cloud:
            config:
               server:
                   git:
                      uri: https://github.com/alanscheibler/microservices-java
                      default-label: main
                      search-paths:
                       - 'configs/{application}'
